source ~/.config/shell/external.sh
source "$XDG_CONFIG_HOME/shell/functions.sh"
source "$XDG_CONFIG_HOME/shell/aliases.sh"

path_append "$USER_BIN_HOME"

# Allow local customizations in the ~/.bashrc_local_before file
if [ -f "$XDG_CONFIG_HOME/zsh/.zshrc_local_before" ]; then
    source "$XDG_CONFIG_HOME/zsh/.zshrc_local_before"
fi

source "$XDG_CONFIG_HOME/zsh/settings.zsh"
source "$XDG_CONFIG_HOME/zsh/plugins.zsh"
