- name: "Install 1Password dekstop"
  tags: "1password"
  shell: |
    cd /tmp
    wget https://downloads.1password.com/linux/debian/amd64/stable/1password-latest.deb
    sudo apt install -y ./1password-latest.deb
    rm -rf 1password-latest.deb
    cd -
