- name: "Install macOS tools"
  hosts: "localhost"
  vars:
    source_key: "../ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tasks:
    - import_tasks: "tasks/macos/gui/1password.yaml"
