- name: "Install Ubuntu tools"
  hosts: "localhost"
  vars:
    source_key: "../ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tasks:
    - import_tasks: "gui/ubuntu/1password.yaml"
    - import_tasks: "terminal/common/ssh.yaml"
    - import_tasks: "terminal/common/secrets.yaml"
