- name: "Install macOS 1Password dekstop"
  tags: "1password"
  when: ansible_os_family == "Darwin"
  block:
    - name: "Check if 1Password desktop is installed"
      command: "[ -d /Applications/1Password.app ]"
      register: one_password_installed
      failed_when: false
    - name: "Install 1Password desktop"
      when: one_password_installed.rc != 0
      shell: |
        cd /tmp
        curl -O https://downloads.1password.com/mac/1Password.zip
        unzip -q 1Password.zip
        open 1Password\ Installer.app
