- name: "Install 1Password dekstop"
  tags: "1password"
  shell: |
    cd /tmp
    curl -O https://downloads.1password.com/mac/1Password.zip
    unzip -q 1Password.zip
    open 1Password\ Installer.app
